@startuml listUnknownDeviceModels
skinparam responseMessageBelowArrow true

title
  listUnknownDeviceModels
end title

participant "requestor\n" as requestor
participant "listUnknownDeviceModels\n" as indServ
database "RunningDS" as RunDS

requestor -> indServ
activate indServ

  note over indServ
    Retrieves
    [DeviceModels]
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  loop for each Device
    note over indServ
      Retrieves deviceModel
    end note
    indServ -> RunDS
    activate RunDS
    indServ <-- RunDS
    deactivate RunDS
    note over indServ
      If deviceModel NOT equal to
      any name in [DeviceModels]
    end note
    note right indServ
      THEN
    end note
    note right indServ
      Appends deviceModel to
      [unknownDeviceModelList]
    end note
    note over indServ
      ELSE
    end note
  end loop

requestor <-- indServ: { [unknownDeviceModelList] }
deactivate indServ

@enduml
