@startuml addOrUpdateTargetFirmware
skinparam responseMessageBelowArrow true

title
  addOrUpdateTargetFirmware
end title

participant "requestor\n" as requestor
participant "addOrUpdateTargetFirmware\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { deviceGroupLabel,\nfirmwareResourceName,\nfirmwareResourceVersion,\nfirmwareStatus }
activate indServ

  note over indServ
    Checks whether given
    deviceGroupLabel exists
    by reading deviceModel
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF DeviceGroup NOT existing:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage,\n[attributeList] }
  note over indServ
    ELSE
  end note

  note over indServ
    Checks whether given combination
    of firmwareResourceName and
    firmwareResourceVersion has 
    been approved for deviceModel
  end note
  note over indServ
    Read [approval] from deviceModel
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF given FirmwareResource NOT in [approval]:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage }
  note over indServ
    ELSE
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note over indServ
    Checks whether given combination
    of firmwareResourceName and
    firmwareResourceVersion already
    referenced in targetFirmwareList
    of given DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS
  note over indServ
    IF FirmwareResource already
    referenced in targetFirmwareList:
  end note
  note right indServ
    THEN
  end note
  note right indServ
    Updates status of TargetFirmware
  end note
  indServ -> CanDS
  indServ <-- CanDS
  note right indServ
    ELSE
  end note
  note right indServ
    Creates new TargetFirmware entry
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Replicates updated target
    into Devices of DeviceGroup
  end note
  note left valiMan #Yellow
    Attention:
    There is no protection against
    too many TargetFirmware or wrong
    compositions of TargetFirmware!
  end note
  note right indServ
    Reads device list 
    of DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS
  loop for each referenced Device
    note right indServ
      Replicates changes into
      firmwareList of the Device
    end note
    indServ -> CanDS
    indServ <-- CanDS
  end loop

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==addOrUpdateTargetFirmware}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note right indServ
    THEN
  end note
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  requestor <-- indServ: { ErrorCode,\nErrorMessage }
  note over indServ
    ELSE
  end note

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

requestor <-- indServ: 204
deactivate indServ

@enduml
