@startuml addOrUpdateTargetFirmware
skinparam responseMessageBelowArrow true

title
  addOrUpdateTargetFirmware
end title

participant "requestor\n" as requestor
participant "addOrUpdateTargetFirmware\n" as cur
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> cur: { deviceGroupLabel,\nfirmwareResourceName,\nfirmwareResourceVersion,\nfirmwareStatus }
activate cur

  note over cur
    Checks whether given
    deviceGroupLabel exists
    by reading deviceModel
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS
  note over cur
    IF DeviceGroup NOT existing:
  end note
  note left cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage,\n[attributeList] }
  note over cur
    ELSE
  end note

  note over cur
    Checks whether given combination
    of firmwareResourceName and
    firmwareResourceVersion has 
    been approved for deviceModel
  end note
  note over cur
    Read [approval] from deviceModel
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS
  note over cur
    IF given FirmwareResource NOT in [approval]:
  end note
  note left cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage }
  note over cur
    ELSE
  end note

  note over cur
    Locks RunningDS
  end note
  cur -X RunDS
  activate RunDS
  note over cur
    Locks CandidateDS
  end note
  cur -X CanDS
  activate CanDS
  note over cur
    Overwrites
    CandidateDS
    with RunningDS
  end note
  cur -> RunDS
  RunDS -/ CanDS

  note over cur
    Checks whether given combination
    of firmwareResourceName and
    firmwareResourceVersion already
    referenced in targetFirmwareList
    of given DeviceGroup
  end note
  cur -> CanDS
  cur <-- CanDS
  note over cur
    IF FirmwareResource already
    referenced in targetFirmwareList:
  end note
  note right cur
    THEN
  end note
  note right cur
    Updates status of TargetFirmware
  end note
  cur -> CanDS
  cur <-- CanDS
  note right cur
    ELSE
  end note
  note right cur
    Creates new TargetFirmware entry
  end note
  cur -> CanDS
  cur <-- CanDS

  note over cur
    Replicates updated target
    into Devices of DeviceGroup
  end note
  note left valiMan #Yellow
    Attention:
    There is no protection against
    too many TargetFirmware or wrong
    compositions of TargetFirmware!
  end note
  note right cur
    Reads device list 
    of DeviceGroup
  end note
  cur -> CanDS
  cur <-- CanDS
  loop for each referenced Device
    note right cur
      Replicates changes into
      firmwareList of the Device
    end note
    cur -> CanDS
    cur <-- CanDS
  end loop

  note over cur
    Triggers Validation
  end note
  cur -> valiMan: {triggerFunction==addOrUpdateTargetFirmware}
  activate valiMan
    note over valiMan
      Validates
    end note
  cur <-- valiMan
  deactivate valiMan
  note over cur
    IF validation failed:
  end note
  note right cur
    THEN
  end note
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  requestor <-- cur: { ErrorCode,\nErrorMessage }
  note over cur
    ELSE
  end note

  note right cur
    Overwrites RunningDS
    with CandidateDS
  end note
  cur -> CanDS
  CanDS -\ RunDS
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  deactivate CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  deactivate RunDS

requestor <-- cur: 204
deactivate cur

@enduml
