@startuml deleteDeviceModel
skinparam responseMessageBelowArrow true

title
  deleteDeviceModel
end title

participant "requestor\n" as requestor
participant "deleteDeviceModel\n" as cur
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> cur: { deviceModelName }
activate cur

  note over cur
    Checks whether given
    deviceModelName exists
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS
  note over cur
    IF DeviceModel NOT existing:
  end note
  note left cur
    THEN
  end note
  requestor <-- cur: 204
  note over cur
    ELSE
  end note

  note over cur
    Checks, whether there are any Devices
    of the to be deleted DeviceModel
  end note
  loop for each existing DeviceGroup
    note over cur
      Checks, whether _deviceModel
      in DeviceGroup references the
      given DeviceModel
    end note
    cur -> RunDS
    activate RunDS
    cur <-- RunDS
    deactivate RunDS
    note over cur
      <color:LightGray>Stores result for later use</color>
      <color:LightGray>in [referencingDeviceGroups]</color>
    end note
    note over cur
      IF given DeviceModel referenced:
    end note
    note right cur
      THEN
    end note
      note right cur
        Reads Devices that are
        referenced in _devices
      end note
      cur -> RunDS
      activate RunDS
      cur <-- RunDS
      deactivate RunDS
      note right cur
        <color:LightGray>Appends result for later use</color>
        <color:LightGray>in [listOfReferencingObjects]</color>
      end note
    note over cur
      ELSE
    end note
  end loop
  note over cur
    IF entries in [listOfReferencingObjects]:
  end note
  note left cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage,\n[listOfReferencingObjects] }
  note over cur
    ELSE
  end note

  note over cur
    Locks RunningDS
  end note
  cur -X RunDS
  activate RunDS
  note over cur
    Locks CandidateDS
  end note
  cur -X CanDS
  activate CanDS
  note over cur
    Overwrites
    CandidateDS
    with RunningDS
  end note
  cur -> RunDS
  RunDS -/ CanDS

  note over cur
    Deletes referencing
    DeviceGroups
  end note
  loop for [referencingDeviceGroups]
    note right cur
      Deletes DeviceGroup
    end note
    cur -> CanDS
    cur <-- CanDS
  end loop

  note right cur
    Deletes given DeviceModel
  end note
  cur -> CanDS
  cur <-- CanDS

  note over cur
    Triggers Validation
  end note
  cur -> valiMan: {triggerFunction==deleteDeviceModel}
  activate valiMan
    note over valiMan
      Validates
    end note
  cur <-- valiMan
  deactivate valiMan
  note over cur
    IF validation failed:
  end note
  note right cur
    THEN
  end note
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  requestor <-- cur: { ErrorCode,\nErrorMessage }
  note over cur
    ELSE
  end note

  note right cur
    Overwrites RunningDS
    with CandidateDS
  end note
  cur -> CanDS
  CanDS -\ RunDS
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  deactivate CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  deactivate RunDS

requestor <-- cur: 204
deactivate cur

@enduml
