@startuml deleteDeviceModel
skinparam responseMessageBelowArrow true

title
  deleteDeviceModel
end title

participant "requestor\n" as requestor
participant "deleteDeviceModel\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { deviceModelName }
activate indServ

  note over indServ
    Checks whether given
    deviceModelName exists
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF DeviceModel NOT existing:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: 204
  note over indServ
    ELSE
  end note

  note over indServ
    Checks, whether there are any Devices
    of the to be deleted DeviceModel
  end note
  loop for each existing DeviceGroup
    note over indServ
      Checks, whether _deviceModel
      in DeviceGroup references the
      given DeviceModel
    end note
    indServ -> RunDS
    activate RunDS
    indServ <-- RunDS
    deactivate RunDS
    note over indServ
      IF given DeviceModel referenced:
    end note
    note right indServ
      THEN
    end note
      note right indServ
        Reads Devices that are
        referenced in _devices
      end note
      indServ -> RunDS
      activate RunDS
      indServ <-- RunDS
      deactivate RunDS
    note over indServ
      ELSE
    end note
  end loop
  note over indServ
    IF Devices of the to be
    deleted DeviceModel found:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage,\n[listOfReferencingObjects] }
  note over indServ
    ELSE
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note over indServ
    Deletes referencing
    DeviceGroups
  end note
  loop for each existing DeviceGroup
    note over indServ
      Reads deviceModel
    end note
    indServ -> CanDS
    indServ <-- CanDS
    note over indServ
      IF given DeviceModel referenced:
    end note
    note right indServ
      THEN
    end note
    note right indServ
      Deletes DeviceGroup
    end note
    indServ -> CanDS
    indServ <-- CanDS
    note over indServ
      ELSE
    end note
  end loop

  note right indServ
    Deletes given DeviceModel
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==deleteDeviceModel}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage }
  note over indServ
    ELSE
  end note

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

  requestor <-- indServ: 204

deactivate indServ

@enduml
