@startuml deleteFirmwareResource
skinparam responseMessageBelowArrow true

title
  deleteFirmwareResource
end title

participant "requestor\n" as requestor
participant "deleteFirmwareResource\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { firmwareResourceName,\nfirmwareResourceVersion }
activate indServ

  note over indServ
    Checks, whether FirmwareResource
    with given combination of name and
    version exists
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF FirmwareResource NOT existing:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: 204
  note over indServ
    ELSE
  end note

  note over indServ
    Checks, whether any
    existing DeviceGroup
    is referencing given
    FirmwareResource
  end note
  loop for each existing DeviceGroup
    indServ -> RunDS
    activate RunDS
    indServ <-- RunDS
    deactivate RunDS
  end loop
  note over indServ
    IF FirmwareResource still referenced:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage,\n[listOfReferencingObjects] }
  note over indServ
    ELSE
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note over indServ
    Cleans up references
  end note
  loop for each existing DeviceModel
    note over indServ
      Checks, whether there is an 
      approval of the to be deleted
      FirmwareResource documented
    end note
    indServ -> CanDS
    indServ <-- CanDS
    note over indServ
      IF approval exists:
    end note
    note right indServ
      THEN
    end note
    note right indServ
      Deletes approval of the
      given FirmwareResource
      from the DeviceModel
    end note
    indServ -> CanDS
    indServ <-- CanDS
  end loop

  note right indServ
    Deletes given FirmwareResource
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==deleteFirmwareResource}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note right indServ
    THEN
  end note
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  requestor <-- indServ: { ErrorCode,\nErrorMessage }
  note over indServ
    ELSE
  end note

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

  requestor <-- indServ: 204

deactivate indServ

@enduml
