@startuml deleteFirmwareResource
skinparam responseMessageBelowArrow true

title
  deleteFirmwareResource
end title

participant "requestor\n" as requestor
participant "deleteFirmwareResource\n" as delFWR
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> delFWR: { firmwareResourceName,\nfirmwareResourceVersion }
activate delFWR

  note over delFWR #LightCoral
    unlock bei Validierungsfehler?
  end note

  note over delFWR
    Checks, whether FirmwareResource
    with given combination of name and
    version exists
  end note
  delFWR -> RunDS
  activate RunDS
  delFWR <-- RunDS
  deactivate RunDS
  note over delFWR
    IF FirmwareResource NOT existing:
  end note
  note left delFWR
    THEN
  end note
  requestor <-- delFWR: 204
  note over delFWR
    ELSE
  end note

  note over delFWR
    Checks, whether any
    existing DeviceGroup
    is referencing given
    FirmwareResource
  end note
  loop for each existing DeviceGroup
    delFWR -> RunDS
    activate RunDS
    delFWR <-- RunDS
    deactivate RunDS
  end loop
  note over delFWR
    IF FirmwareResource still referenced:
  end note
  note left delFWR
    THEN
  end note
  requestor <-- delFWR: { ErrorCode,\nErrorMessage,\n[listOfReferencingObjects] }
  note over delFWR
    ELSE
  end note

  note over delFWR
    Locks RunningDS
  end note
  delFWR -X RunDS
  activate RunDS
  note over delFWR
    Locks CandidateDS
  end note
  delFWR -X CanDS
  activate CanDS
  note over delFWR
    Overwrites
    CandidateDS
    with RunningDS
  end note
  delFWR -> RunDS
  RunDS -/ CanDS

  note over delFWR
    Cleans up references
  end note
  loop for each existing DeviceModel
    note over delFWR
      Checks, whether there is an 
      approval of the to be deleted
      FirmwareResource documented
    end note
    delFWR -> CanDS
    delFWR <-- CanDS
    note over delFWR
      IF approval exists:
    end note
    note right delFWR
      THEN
    end note
    note right delFWR
      Deletes approval of the
      given FirmwareResource
      from the DeviceModel
    end note
    delFWR -> CanDS
    delFWR <-- CanDS
  end loop

  note right delFWR
    Deletes given FirmwareResource
  end note
  delFWR -> CanDS
  delFWR <-- CanDS

  note over delFWR
    Triggers Validation
  end note
  delFWR -> valiMan: {triggerFunction==deleteFirmwareResource}
  activate valiMan
    note over valiMan
      Validates
    end note
  delFWR <-- valiMan
  deactivate valiMan
  note over delFWR
    IF validation failed:
  end note
  note left delFWR
    THEN
  end note
  requestor <-- delFWR: { ErrorCode,\nErrorMessage }
  note over delFWR
    ELSE
  end note

  note right delFWR
    Overwrites RunningDS
    with CandidateDS
  end note
  delFWR -> CanDS
  CanDS -\ RunDS
  note right delFWR
    Unlocks CandidateDS
  end note
  delFWR -X CanDS
  deactivate CanDS
  note right delFWR
    Unlocks RunningDS
  end note
  delFWR -X RunDS
  deactivate RunDS

  requestor <-- delFWR: 204

deactivate delFWR

@enduml
