@startuml createOrUpdateFirmwareResource
skinparam responseMessageBelowArrow true

title
  createOrUpdateFirmwareResource
end title

participant "requestor\n" as requestor
participant "createOrUpdateFirmwareResource\n" as cur
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> cur: { firmwareResourceName,\nfirmwareResourceVersion,\n<color:LightGray>serverLabel,\n<color:LightGray>sourceUri,\n<color:LightGray>fileName</color> }
activate cur

  note over cur
    Checks, whether given
    combination of
    firmwareResourceName and
    firmwareResourceVersion
    already documented
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS
  note over cur
    IF FirmwareResource NOT already existing:
  end note
  note right cur
    THEN
  end note
  note right cur
    Checks whether serverLabel,
    sourceUri and fileName are
    all given
  end note
  note right cur
    IF NOT all attributes given:
  end note
  note right cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage,\n[attributeList] }
  note right cur
    ELSE
  end note
  note over cur
    ELSE
  end note

  note over cur
    IF serverLabel given:
  end note
  note right cur
    THEN:
  end note
  note right cur
    Checks whether
    Server exists
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS
  note right cur
    IF Server NOT existing:
  end note
  note right cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage,\n[attributeList] }
  note right cur
    ELSE
  end note
  note over cur
    ELSE
  end note

  note over cur
    Checks, whether given
    combination of serverLabel,
    sourceUri and fileName
    already documented
  end note
  loop for each existing FirmwareResource
    cur -> RunDS
    activate RunDS
    cur <-- RunDS
    deactivate RunDS
  end loop
  note over cur
    IF source already documented:
  end note
  note left cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage,\nfirmwareResourceName }
  note over cur
    ELSE
  end note

  note over cur
    Locks RunningDS
  end note
  cur -X RunDS
  activate RunDS
  note over cur
    Locks CandidateDS
  end note
  cur -X CanDS
  activate CanDS
  note over cur
    Overwrites
    CandidateDS
    with RunningDS
  end note
  cur -> RunDS
  RunDS -/ CanDS

  note over cur
    Checks for existing
    FirmwareResource with
    given name and version
  end note
  cur -> CanDS
  cur <-- CanDS
  note over cur
    IF combination of firmwareResourceName
    and firmwareResourceVersion already exists:
  end note
  note right cur
    THEN
    - Updates existing FirmwareResource
  end note
  cur -> CanDS
  cur <-- CanDS
  note right cur
    ELSE
    - Creates new FirmwareResource
  end note
  cur -> CanDS
  cur <-- CanDS

  note over cur
    Triggers Validation
  end note
  cur -> valiMan: {triggerFunction==createOrUpdateFirmwareResource}
  activate valiMan
    note over valiMan
      Validates
    end note
  cur <-- valiMan
  deactivate valiMan
  note over cur
    IF validation failed:
  end note
  note right cur
    THEN
  end note
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  requestor <-- cur: { ErrorCode,\nErrorMessage }
  note over cur
    ELSE
  end note

  note right cur
    Overwrites RunningDS
    with CandidateDS
  end note
  cur -> CanDS
  CanDS -\ RunDS
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  deactivate CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  deactivate RunDS

requestor <-- cur: 204
deactivate cur

@enduml
