@startuml createOrUpdateFirmwareResource
skinparam responseMessageBelowArrow true

title
  createOrUpdateFirmwareResource
end title

participant "requestor\n" as requestor
participant "createOrUpdateFirmwareResource\n" as couFWR
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> couFWR: { firmwareResourceName,\nfirmwareResourceVersion,\n<color:LightGray>serverLabel,\n<color:LightGray>sourceUri,\n<color:LightGray>fileName</color> }
activate couFWR

  note over couFWR
    Checks, whether given
    combination of
    firmwareResourceName and
    firmwareResourceVersion
    already documented
  end note
  couFWR -> RunDS
  activate RunDS
  couFWR <-- RunDS
  deactivate RunDS
  note over couFWR
    IF FirmwareResource NOT already existing:
  end note
  note right couFWR
    THEN
  end note
  note right couFWR
    Checks whether serverLabel,
    sourceUri and fileName are
    all given
  end note
  note right couFWR
    IF NOT all attributes given:
  end note
  note right couFWR
    THEN
  end note
  requestor <-- couFWR: { ErrorCode,\nErrorMessage,\n[attributeList] }
  note right couFWR
    ELSE
  end note
  note over couFWR
    ELSE
  end note

  note over couFWR
    IF serverLabel given:
  end note
  note right couFWR
    THEN:
  end note
  note right couFWR
    Checks whether
    Server exists
  end note
  couFWR -> RunDS
  activate RunDS
  couFWR <-- RunDS
  deactivate RunDS
  note right couFWR
    IF Server NOT existing:
  end note
  note right couFWR
    THEN
  end note
  requestor <-- couFWR: { ErrorCode,\nErrorMessage,\n[attributeList] }
  note right couFWR
    ELSE
  end note
  note over couFWR
    ELSE
  end note

  note over couFWR
    Checks, whether given
    combination of serverLabel,
    sourceUri and fileName
    already documented
  end note
  loop for each existing FirmwareResource
    couFWR -> RunDS
    activate RunDS
    couFWR <-- RunDS
    deactivate RunDS
  end loop
  note over couFWR
    IF source already documented:
  end note
  note left couFWR
    THEN
  end note
  requestor <-- couFWR: { ErrorCode,\nErrorMessage,\nfirmwareResourceName }
  note over couFWR
    ELSE
  end note

  note over couFWR
    Locks RunningDS
  end note
  couFWR -X RunDS
  activate RunDS
  note over couFWR
    Locks CandidateDS
  end note
  couFWR -X CanDS
  activate CanDS
  note over couFWR
    Overwrites
    CandidateDS
    with RunningDS
  end note
  couFWR -> RunDS
  RunDS -/ CanDS

  note over couFWR
    Checks for existing
    FirmwareResource with
    given name and version
  end note
  couFWR -> CanDS
  couFWR <-- CanDS
  note over couFWR
    IF combination of firmwareResourceName
    and firmwareResourceVersion already exists:
  end note
  note right couFWR
    THEN
    - Updates existing FirmwareResource
  end note
  couFWR -> CanDS
  couFWR <-- CanDS
  note right couFWR
    ELSE
    - Creates new FirmwareResource
  end note
  couFWR -> CanDS
  couFWR <-- CanDS

  note over couFWR
    Triggers Validation
  end note
  couFWR -> valiMan: {triggerFunction==createOrUpdateFirmwareResource}
  activate valiMan
    note over valiMan
      Validates
    end note
  couFWR <-- valiMan
  deactivate valiMan
  note over couFWR
    IF validation failed:
  end note
  note left couFWR
    THEN
  end note
  requestor <-- couFWR: { ErrorCode,\nErrorMessage }
  note over couFWR
    ELSE
  end note

  note right couFWR
    Overwrites RunningDS
    with CandidateDS
  end note
  couFWR -> CanDS
  CanDS -\ RunDS
  note right couFWR
    Unlocks CandidateDS
  end note
  couFWR -X CanDS
  deactivate CanDS
  note right couFWR
    Unlocks RunningDS
  end note
  couFWR -X RunDS
  deactivate RunDS

  requestor <-- couFWR: 204

deactivate couFWR

@enduml
