@startuml p1DeleteDevices
skinparam responseMessageBelowArrow true

title
  p1DeleteDevices
end title

participant "pulser\n" as pulser
participant "p1DeleteDevices\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS
database "OperationalDS" as OpDS
database "DomainController" as DC

pulser -> indServ
activate indServ

  note over indServ
    Reads parameters
    from DomainController
  end note
    indServ -> DC
    activate DC
    indServ <-- DC: { maximumPermissibleAge }
    deactivate DC

  loop for each ODS:Device
    note over indServ
      Checks, whether lastUpdate
      exceeds maximumPermissibleAge
    end note
    indServ -> OpDS
    activate OpDS
    indServ <-- OpDS
    deactivate OpDS
    note over indServ
      IF lastUpdate exceeds
      maximumPermissibleAge:
    end note
    note right indServ
      THEN
    end note
    note right indServ
      Deletes obsolete ODS:Devices
    end note
    indServ -> OpDS
    activate OpDS
    indServ <-- OpDS
    deactivate OpDS

    note right indServ
      Appends mountName and deviceModel
      of ODS:Device to [obsoleteDevice]
    end note
    note over indServ
      ELSE
    end note
  end loop
  note over indServ
    IF [obsoleteDevice].length = 0:
  end note
  note left indServ
    THEN
  end note
  pulser <-- indServ: 204
  note over indServ
    ELSE
  end note  

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  loop for [obsoleteDevice]
    note over indServ
      Deletes obsolete RDS:Device
    end note
    indServ -> CanDS
    indServ <-- CanDS

    loop for each DeviceGroup
      note over indServ
        Retrieve deviceModel
      end note
      indServ -> CanDS
      indServ <-- CanDS
      note over indServ
        IF DeviceGroup:deviceModel 
              = obsoleteDevice:deviceModel:
      end note
      note right indServ
        THEN
      end note
      note right indServ
        Check, whether obsoleteDevice:mountName
        is contained in DeviceGroup:[device]
      end note
      note right indServ
        _IF obsoleteDevice referenced by DeviceGroup:
      end note
      note right indServ
        _THEN
      end note
      note right indServ
        Remove obsoleteDevice:mountName
        from DeviceGroup:[device]
      end note
      note right indServ
        _ELSE
      end note
      note over indServ
        ELSE
      end note
    end loop
  end loop

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

pulser <-- indServ: 204
deactivate indServ

@enduml
