@startuml p1DeleteDevices
skinparam responseMessageBelowArrow true

title
  p1DeleteDevices
end title

participant "pulser\n" as pulser
participant "p1DeleteDevices\n" as cur
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS
database "OperationalDS" as OpDS
database "DomainController" as DC

pulser -> cur
activate cur

  ' Get retention period settings
  note over cur
    Reads parameters
    from DomainController
  end note
    cur -> DC
    activate DC
    cur <-- DC: { maximumPermissibleAge }
    deactivate DC

  ' Iterate over ODS devices to check for obsolescence
  loop for each ODS:Device
    note over cur
      Checks, whether lastUpdate
      exceeds maximumPermissibleAge
    end note
    cur -> OpDS
    activate OpDS
    cur <-- OpDS
    deactivate OpDS
    note over cur
      IF lastUpdate exceeds
      maximumPermissibleAge:
    end note
    note right cur
      THEN
    end note
    note right cur
      Deletes obsolete ODS:Devices
    end note
    cur -> OpDS
    activate OpDS
    cur <-- OpDS
    deactivate OpDS

    note right cur
      Appends mountName and deviceModel
      of ODS:Device to [obsoleteDevice]
    end note
    note over cur
      ELSE
    end note
  end loop

  ' If nothing to delete: finished
  note over cur
    IF [obsoleteDevice].length = 0:
  end note
  note left cur
    THEN
  end note
  pulser <-- cur: 204
  note over cur
    ELSE
  end note  

  ' Else copy RDS to CDS
  note over cur
    Locks RunningDS
  end note
  cur -X RunDS
  activate RunDS
  note over cur
    Locks CandidateDS
  end note
  cur -X CanDS
  activate CanDS
  note over cur
    Overwrites
    CandidateDS
    with RunningDS
  end note
  cur -> RunDS
  RunDS -/ CanDS

  ' Delete obsolete devices from CDS
  loop for [obsoleteDevice]
    note over cur
      Deletes obsolete RDS:Device
    end note
    cur -> CanDS
    cur <-- CanDS

    loop for each DeviceGroup
      note over cur
        Retrieve deviceModel
      end note
      cur -> CanDS
      cur <-- CanDS
      note over cur
        IF DeviceGroup:deviceModel 
              = obsoleteDevice:deviceModel:
      end note
      note right cur
        THEN
      end note
      note right cur
        Check, whether obsoleteDevice:mountName
        is contained in DeviceGroup:[device]
      end note
      note right cur
        _IF obsoleteDevice referenced by DeviceGroup:
      end note
      note right cur
        _THEN
      end note
      note right cur
        Remove obsoleteDevice:mountName
        from DeviceGroup:[device]
      end note
      note right cur
        _ELSE
      end note
      note over cur
        ELSE
      end note
    end loop
  end loop

  ' Write updated CDS back to RDS
  note right cur
    Overwrites RunningDS
    with CandidateDS
  end note
  cur -> CanDS
  CanDS -\ RunDS
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  deactivate CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  deactivate RunDS

pulser <-- cur: 204
deactivate cur

@enduml
