@startuml listDeviceGroupsWithoutDevices
skinparam responseMessageBelowArrow true

title
  listDeviceGroupsWithoutDevices
end title

participant "requestor\n" as requestor
participant "listDeviceGroupsWithoutDevices\n" as cur
database "RunningDS" as RunDS

requestor -> cur
activate cur

    note over cur
      Retrieves [DeviceGroups]
    end note
    cur -> RunDS
    activate RunDS
    cur <-- RunDS
    deactivate RunDS

  loop for each DeviceGroup
    note over cur
      If [device].length NOT > 0
    end note
    note right cur
      THEN
    end note
    note right cur
      Appends label of DeviceGroup
      to [deviceGroupList]
    end note
    note over cur
      ELSE
    end note
  end loop

requestor <-- cur: { [deviceGroupList] }
deactivate cur

@enduml
