@startuml measurement_ideas
skinparam responseMessageBelowArrow true

title
  Measurement Ideas
end title

participant "requestor\n" as requestor
participant "p1MeasureDomain\n" as indServ
participant "p1ListUpdatedCcs\n" as listCcs
participant "p1UpdateDevice\n" as updateCc
participant "p1UpdateHw\n" as updateHw
participant "p1WriteJust\nDeviceModel" as writeModel
participant "p1UpdateFw\n" as updateFw
participant "p1Extract\nActivatable" as extractAct

database "OperationalDS" as OpDS
database "MWDI" as Mwdi

requestor -> indServ
activate indServ
  note over indServ
    Updates
    OperationalDS
  end note

  indServ -> listCcs
  activate listCcs
    note over listCcs
      Lists CCs that are
      updated in MWDI
    end note
  indServ <-- listCcs: [updatedMountName]
  deactivate listCcs

  group partially parallel execution of each updatedMountName
    indServ -> updateCc
    activate updateCc
      note over updateCc
        Updates Device
        in OperationalDS
      end note

      note over updateCc
        Reads CC
      end note
      updateCc -> Mwdi: updatedMountName
      activate Mwdi
      updateCc <-- Mwdi: CC
      deactivate Mwdi

      note over updateCc
        Updates hardware info
      end note
      updateCc -> updateHw: updatedMountName,\nCC
      activate updateHw
        note over updateHw
          Updates device model
          specific hardware
          dependencies
        end note

        note over updateHw
          Extracts deviceModel
        end note

        note over updateHw
          Reads name of extraction
          function from Parameters
        end note
        updateHw -> OpDS: deviceModel
        activate OpDS
        updateHw <-- OpDS: functionName
        deactivate OpDS
        note over updateFw #White
          Parameters cannot define set of input parameters.
          All functions get called with updatedMountName and CC.
        end note

        note over updateHw
          Calls functionName to
          extract hardware info
          and update OperationalDS
        end note
        updateHw -> writeModel: updatedMountName,\nCC
        activate writeModel
          note over writeModel
            Extracts deviceModel
          end note
          note over writeModel
            Writes deviceModel
            into OperationalDS
          end note
          writeModel -> OpDS: deviceModel
        updateHw <-- writeModel
        deactivate writeModel
      updateCc <-- updateHw
      deactivate updateHw

      note over updateCc
        Updates firmware info
      end note
      updateCc -> updateFw: updatedMountName,\nCC
      activate updateFw
        note over updateFw
          Updates device model
          specific firmware
          composition
        end note

        note over updateFw
          Extracts deviceModel
        end note

        note over updateFw
          Reads name of extraction
          function from Parameters
        end note
        updateFw -> OpDS: deviceModel
        activate OpDS
        updateFw <-- OpDS: functionName
        deactivate OpDS
        note over updateHw #White
          Parameters cannot define set of input parameters.
          All functions get called with updatedMountName and CC.
        end note

        note over updateFw
          Calls functionName to
          extract firmware info
          and update OperationalDS
        end note
        updateFw -> extractAct: updatedMountName,\nCC
        activate extractAct
          note over extractAct
            Extracts activatable
            firmware
          end note
          note over extractAct
            Converts firmware info
            into [firmwareList]
          end note
          note over extractAct
            Writes [firmwareList]
          end note
          extractAct -> OpDS: [firmwareList]
        updateFw <-- extractAct
        deactivate extractAct
      updateCc <-- updateFw
      deactivate updateFw

      note over updateCc
        Updates lastUpdate
      end note
      updateCc -> OpDS: lastUpdate

    indServ <-- updateCc
    deactivate updateCc
  end group updatedMountNames

requestor <-- indServ
deactivate indServ

@enduml
