@startuml embedYourself
skinparam responseMessageBelowArrow true

title
  embedYourself
end title

participant "RegistryOffice\n" as RO
participant "embedYourself\n" as embed
participant "bequeathYourDataAndDie\n" as bequeath

participant "p1ManageFirmware\n" as manaFW


RO -> embed
activate embed

  embed -> bequeath
  activate bequeath
    note over bequeath
      [further steps for handing over
      data potentially to be added]
    end note
  embed <-- bequeath : 204
  deactivate bequeath

  note over embed
    [further steps of the embedding
    process potentially to be added]
  end note

  note right embed
    Automatically start
    p1ManageFirmware
  end note
  embed -> manaFW
  activate manaFW

deactivate embed

@enduml
