@startuml listExistingFirmwareResources
skinparam responseMessageBelowArrow true

title
  listExistingFirmwareResources
end title

participant "requestor\n" as requestor
participant "listExistingFirmwareResources\n" as indServ
database "RunningDS" as RunDS

requestor -> indServ
activate indServ

  note over indServ
    Retrieves data
    from RunningDS
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS

requestor <-- indServ: [ { firmwareResourceName,\nfirmwareResourceVersion,\nserverLabel,\nsourceUri,\nfileName } ]
deactivate indServ

@enduml
