@startuml listExistingFirmwareResources
skinparam responseMessageBelowArrow true

title
  listExistingFirmwareResources
end title

participant "requestor\n" as requestor
participant "listExistingFirmwareResources\n" as lResources
database "RunningDS" as RunDS

requestor -> lResources
activate lResources

  note over lResources
    Retrieves data
    from RunningDS
  end note
  lResources -> RunDS
  activate RunDS
  lResources <-- RunDS
  deactivate RunDS

requestor <-- lResources: [ { name,\nversion,\nserver,\nsource-uri,\nfile-name } ]
deactivate lResources

@enduml
