@startuml listExistingFirmwareResources
skinparam responseMessageBelowArrow true

title
  listExistingFirmwareResources
end title

participant "requestor\n" as requestor
participant "listExistingFirmwareResources\n" as cur
database "RunningDS" as RunDS

requestor -> cur
activate cur

  note over cur
    Retrieves
    FirmwareResources
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS

requestor <-- cur: [ { firmwareResourceName,\nfirmwareResourceVersion,\nserverLabel,\nsourceUri,\nfileName } ]
deactivate cur

@enduml
