@startuml removeFirmwareApproval
skinparam responseMessageBelowArrow true

title
  removeFirmwareApproval
end title

participant "requestor\n" as requestor
participant "removeFirmwareApproval\n" as removeAppro
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> removeAppro: { deviceModelName,\nfirmwareResourceName,\nfirmwareResourceVersion }
activate removeAppro

  note over removeAppro
    Checks, whether firmware approval
    with given combination of name and
    version exists at given DeviceModel
  end note
  removeAppro -> RunDS
  activate RunDS
  removeAppro <-- RunDS
  deactivate RunDS
  note over removeAppro
    IF firmware approval NOT existing:
  end note
  note left removeAppro
    THEN
  end note
  requestor <-- removeAppro: 204
  note over removeAppro
    ELSE
  end note

  note over removeAppro
    Checks, whether to be withdrawn
    firmware approval is still base of
    references as target firmware in
    DeviceGroups
  end note
  loop for each existing DeviceGroup
    note over removeAppro
      Checks, whether _deviceModel 
      matches given deviceModelName
    end note
    removeAppro -> RunDS
    activate RunDS
    removeAppro <-- RunDS
    deactivate RunDS
      note over removeAppro
        IF _deviceModel equals
        given deviceModelName
      end note
      note right removeAppro
        THEN
      end note
      note right removeAppro
        Checks, whether combination of
        given firmwareResourceName and 
        firmwareResourceVersion is in
        targetFirmwareList
      end note
      removeAppro -> RunDS
      activate RunDS
      removeAppro <-- RunDS
      deactivate RunDS
      note over removeAppro
        ELSE
      end note
  end loop
  note over removeAppro
    IF given combination of 
    firmwareResourceName and
    firmwareResourceVersion
    in targetFirmwareList
  end note
  note left removeAppro
    THEN
  end note
  requestor <-- removeAppro: { ErrorCode,\nErrorMessage,\n[listOfReferencingObjects] }
  note over removeAppro
    ELSE
  end note

  note over removeAppro
    Locks RunningDS
  end note
  removeAppro -X RunDS
  activate RunDS
  note over removeAppro
    Locks CandidateDS
  end note
  removeAppro -X CanDS
  activate CanDS
  note over removeAppro
    Overwrites
    CandidateDS
    with RunningDS
  end note
  removeAppro -> RunDS
  RunDS -/ CanDS

  note right removeAppro
    Deletes given firmware approval
  end note
  removeAppro -> CanDS
  removeAppro <-- CanDS

  note over removeAppro
    Triggers Validation
  end note
  removeAppro -> valiMan: {triggerFunction==removeFirmwareApproval}
  activate valiMan
    note over valiMan
      Validates
    end note
  removeAppro <-- valiMan
  deactivate valiMan
  note over removeAppro
    IF validation failed:
  end note
  note left removeAppro
    THEN
  end note
  requestor <-- removeAppro: { ErrorCode,\nErrorMessage }
  note over removeAppro
    ELSE
  end note

  note right removeAppro
    Overwrites RunningDS
    with CandidateDS
  end note
  removeAppro -> CanDS
  CanDS -\ RunDS
  note right removeAppro
    Unlocks CandidateDS
  end note
  removeAppro -X CanDS
  deactivate CanDS
  note right removeAppro
    Unlocks RunningDS
  end note
  removeAppro -X RunDS
  deactivate RunDS

  requestor <-- removeAppro: 204

deactivate removeAppro

@enduml
