@startuml removeFirmwareApproval
skinparam responseMessageBelowArrow true

title
  removeFirmwareApproval
end title

participant "requestor\n" as requestor
participant "removeFirmwareApproval\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { deviceModelName,\nfirmwareResourceName,\nfirmwareResourceVersion }
activate indServ

  note over indServ
    Checks, whether firmware approval
    with given combination of name and
    version exists at given DeviceModel
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF firmware approval NOT existing:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: 204
  note over indServ
    ELSE
  end note

  note over indServ
    Checks, whether to be withdrawn
    firmware approval is still base of
    references as target firmware in
    DeviceGroups
  end note
  loop for each existing DeviceGroup
    note over indServ
      Checks, whether _deviceModel 
      matches given deviceModelName
    end note
    indServ -> RunDS
    activate RunDS
    indServ <-- RunDS
    deactivate RunDS
      note over indServ
        IF _deviceModel equals
        given deviceModelName
      end note
      note right indServ
        THEN
      end note
      note right indServ
        Checks, whether combination of
        given firmwareResourceName and 
        firmwareResourceVersion is in
        targetFirmwareList
      end note
      indServ -> RunDS
      activate RunDS
      indServ <-- RunDS
      deactivate RunDS
      note over indServ
        ELSE
      end note
  end loop
  note over indServ
    IF given combination of 
    firmwareResourceName and
    firmwareResourceVersion
    in targetFirmwareList
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage,\n[listOfReferencingObjects] }
  note over indServ
    ELSE
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note right indServ
    Deletes given firmware approval
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==removeFirmwareApproval}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage }
  note over indServ
    ELSE
  end note

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

  requestor <-- indServ: 204

deactivate indServ

@enduml
