@startuml listExistingDevices
skinparam responseMessageBelowArrow true

title
  listExistingDevices
end title

participant "requestor\n" as requestor
participant "listExistingDevices\n" as indServ
database "RunningDS" as RunDS

requestor -> indServ
activate indServ

  note over indServ
    Retrieves data
    from RunningDS
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS

requestor <-- indServ: [ {mountName,\ndeviceModel,\n[firmwareList]} ]
deactivate indServ

@enduml
