@startuml createOrUpdateServer
skinparam responseMessageBelowArrow true

title
  createOrUpdateServer
end title

participant "requestor\n" as requestor
participant "createOrUpdateServer\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { serverLabel,\n<color:LightGray>userName,\n<color:LightGray>password,\n<color:LightGray>sshKey</color> }
activate indServ

  note over indServ #LightCoral
    (1) Der CandidateDS wird mit dem Inhalt vom RunningDS überschrieben,
    also auch der Server.
    Im InformationStructure Diagram steht aber dass es Server nur
    im RunningDS geben soll (mit <<R>> markiert)
    Ist das nicht inkonsistent?
  end note
  note over indServ #LightCoral
    (2) Wenn die Validierung fehlschlägt:
    - werden die DS nicht unlocked.
    - Sollte die Änderung im Candidate nicht auch u.U. rückgängig gemacht werden?
      (Jenachdem was genau da validiert werden soll...)
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note over indServ
    Checks for existing
    Server with given label
  end note
  indServ -> CanDS
  indServ <-- CanDS
  note over indServ
    IF Server already existing:
  end note
  note right indServ
    THEN
    - Updates existing Server
  end note
  indServ -> CanDS
  indServ <-- CanDS
  note right indServ
    ELSE
    - Creates new Server
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==createOrUpdateServer}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage }
  note over indServ
    ELSE
  end note

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

  requestor <-- indServ: 204

deactivate indServ

@enduml
