@startuml createOrUpdateServer
skinparam responseMessageBelowArrow true

title
  createOrUpdateServer
end title

participant "requestor\n" as requestor
participant "createOrUpdateServer\n" as couServer
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> couServer: { label,\nuserName,\npassword,\nsshKey }
activate couServer

  note over couServer
    Locks RunningDS
  end note
  couServer -X RunDS
  activate RunDS

  note over couServer
    Overwrites
    CandidateDS
    with RunningDS
  end note
  couServer -> RunDS
  RunDS -/ CanDS
  activate CanDS

  note over couServer
    Checks for existing
    server instance
    with given label
  end note
  couServer -> CanDS
  couServer <-- CanDS

  note over couServer
    IF server already existing:
  end note
  note right couServer
    THEN
    - Updates existing server
  end note
  couServer -> CanDS
  couServer <-- CanDS
  note right couServer
    ELSE
    - Creates new server instance
  end note
  couServer -> CanDS
  couServer <-- CanDS

  note over couServer
    Trigger Validation
  end note
  couServer -> valiMan: {triggerFunction==createOrUpdateServer}
  activate valiMan

    note over valiMan
      Validates
    end note

  couServer <-- valiMan
  deactivate valiMan

  note over couServer
    IF successfully validated:
  end note
  note right couServer
    THEN
    - Overwrites RunningDS
      with CandidateDS
    - Sends 204
  end note
  couServer -> CanDS
  CanDS -\ RunDS
  deactivate CanDS
  requestor <-- couServer: 204
  note right couServer
    ELSE
    - Sends ErrorMessage
  end note
  requestor <-- couServer: ErrorMessage

  note right couServer
    Unlocks RunningDS
  end note
  couServer -X RunDS
  deactivate RunDS

deactivate couServer

@enduml
