@startuml createOrUpdateServer
skinparam responseMessageBelowArrow true

title
  createOrUpdateServer
end title

participant "requestor\n" as requestor
participant "createOrUpdateServer\n" as couServer
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> couServer: { serverLabel,\n<color:LightGray>userName,\n<color:LightGray>password,\n<color:LightGray>sshKey</color> }
activate couServer

  note over couServer #LightCoral
    (1) Der CandidateDS wird mit dem Inhalt vom RunningDS überschrieben,
    also auch der Server.
    Im InformationStructure Diagram steht aber dass es Server nur
    im RunningDS geben soll (mit <<R>> markiert)
    Ist das nicht inkonsistent?
  end note
  note over couServer #LightCoral
    (2) Wenn die Validierung fehlschlägt:
    - werden die DS nicht unlocked.
    - Sollte die Änderung im Candidate nicht auch u.U. rückgängig gemacht werden?
      (Jenachdem was genau da validiert werden soll...)
  end note

  note over couServer
    Locks RunningDS
  end note
  couServer -X RunDS
  activate RunDS
  note over couServer
    Locks CandidateDS
  end note
  couServer -X CanDS
  activate CanDS
  note over couServer
    Overwrites
    CandidateDS
    with RunningDS
  end note
  couServer -> RunDS
  RunDS -/ CanDS

  note over couServer
    Checks for existing
    Server with given label
  end note
  couServer -> CanDS
  couServer <-- CanDS
  note over couServer
    IF Server already existing:
  end note
  note right couServer
    THEN
    - Updates existing Server
  end note
  couServer -> CanDS
  couServer <-- CanDS
  note right couServer
    ELSE
    - Creates new Server
  end note
  couServer -> CanDS
  couServer <-- CanDS

  note over couServer
    Triggers Validation
  end note
  couServer -> valiMan: {triggerFunction==createOrUpdateServer}
  activate valiMan
    note over valiMan
      Validates
    end note
  couServer <-- valiMan
  deactivate valiMan
  note over couServer
    IF validation failed:
  end note
  note left couServer
    THEN
  end note
  requestor <-- couServer: { ErrorCode,\nErrorMessage }
  note over couServer
    ELSE
  end note

  note right couServer
    Overwrites RunningDS
    with CandidateDS
  end note
  couServer -> CanDS
  CanDS -\ RunDS
  note right couServer
    Unlocks CandidateDS
  end note
  couServer -X CanDS
  deactivate CanDS
  note right couServer
    Unlocks RunningDS
  end note
  couServer -X RunDS
  deactivate RunDS

  requestor <-- couServer: 204

deactivate couServer

@enduml
