@startuml kmo_p1ListUpdatedCcs
skinparam responseMessageBelowArrow true

title
  kmo_p1ListUpdatedCcs
end title

participant "requestor\n" as requestor
participant "p1ListUpdatedCcs\n" as indServ

database "MWDI" as mwdi

note over requestor
  Updates
  OperationalDS
end note

requestor -> indServ
activate indServ
  note over indServ
    Lists CCs that are
    updated in MWDI
  end note
  note over indServ #Orange
    access MWDI ES index directly,
    possibly get list of udpated
    devices from some redis queue
  end note
  indServ -> mwdi
  indServ <-- mwdi: [updatedMountName]

  note over indServ #LightBlue
    tb discussed:
    general MWDI access error possibly
    could be recorded
    (if the list of udpateMountNames is empty
    this should not be treated as an error)
  end note

requestor <-- indServ: [updatedMountName]
deactivate indServ

@enduml
