@startuml p1ListUpdatedCcs
skinparam responseMessageBelowArrow true

title
  p1ListUpdatedCcs
end title

participant "requestor\n" as requestor
participant "p1ListUpdatedCcs\n" as indServ

database "MWDI" as Mwdi

note over requestor
  Updates
  OperationalDS
end note

requestor -> indServ
activate indServ
  note over indServ
    Lists CCs that are
    updated in MWDI
  end note
  note over indServ #Orange
    Details to be defined
  end note
requestor <-- indServ: [updatedMountName]
deactivate indServ

@enduml
