@startuml p1ListUpdatedCcs
skinparam responseMessageBelowArrow true

title
  p1ListUpdatedCcs
end title

participant "requestor\n" as requestor
participant "p1ListUpdatedCcs\n" as indServ

database "MWDI" as Mwdi

requestor -> indServ
activate indServ
  note over indServ
    Lists CCs that have
    been updated in MWDI
    since last update of
    OperationalDS
  end note
  note over indServ #Orange
    Details to be defined
  end note
requestor <-- indServ: [updatedMountName]
deactivate indServ

@enduml
