openapi: 3.0.0
info:
  title: p1LoadEsAddresses
  version: 1.0.0

x-javascript-interface:
  p1LoadEsAddresses:
    summary: 'Loads ES addresses and makes them available at DomainController'
    processing:
      p1LoadParameters:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - function-name
                properties:
                  function-name:
                    type: string
                    description: >
                      'Name of the Function whose parameters are to be loaded from the configFile
                      from [/load-es-addresses/function-name]'
        output:
          success:
            description: 'Parameters successfully loaded'
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    parameters:
                      type: object
                    config-file:
                      type: object
          error:
            description: 'Parameters could not be loaded'
            content:
              application/json:
                schema:
                  type: string
        documentLoadParametersError:
          input:
            description: 'Adds a new entry to the DomainController historicalErrorList'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - function-name
                    - load-parameters-error
                  properties:
                    function-name:
                      type: string
                      enum:
                        'p1LoadParameters'
                      description: >
                        'Name of function with error
                        written to [/domain-controller/historical-error-list[n]/errored-function]'
                    load-parameters-error:
                      type: string
                      description: >
                        'Error message
                        from [/load-es-addresses/load-parameters-error]
                        written to [/domain-controller/historical-error-list[n]/error-message]'
                    timestamp:
                      type: string
                      pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})$'
                      description: >
                        'Current timestamp. Format: yyyy-mm-ddThh:mm:ss+hh:mm
                        written to [/domain-controller/historical-error-list[n]/timestamp]'
      p1ResolveEsAddress:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - parameters
                  - config-file
                  - es-name
                properties:
                  parameters:
                    type: object
                    description: >
                      'Hierarchical object holding the parameter settings
                      from [/load-es-addresses/parameters/sub-function=p1ResolveEsAddress]'
                  config-file:
                    type: object
                    description: >
                      'configFile content
                      from [/load-es-addresses/config-file]'
                  es-name:
                    type: string
                    description: >
                      'ElasticSearch name
                      from [/load-es-addresses/es-names=*/name]'
        output:
          success:
            description: 'ES address successfully resolved'
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    es-address:
                      type: object
          error:
            description: 'ES address could not be resolved'
            content:
              application/json:
                schema:
                  type: string
        documentResolveEsAddressError:
          input:
            description: 'Adds a new entry to the DomainController historicalErrorList'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - function-name
                    - load-parameters-error
                  properties:
                    function-name:
                      type: string
                      enum:
                        'p1ResolveEsAddress'
                      description: >
                        'Name of function with error
                        written to [/domain-controller/historical-error-list[n]/errored-function]'
                    load-parameters-error:
                      type: string
                      description: >
                        'Error message
                        from [/load-es-addresses/resolve-es-address-error]
                        written to [/domain-controller/historical-error-list[n]/error-message]'
                    timestamp:
                      type: string
                      pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})$'
                      description: >
                        'Current timestamp. Format: yyyy-mm-ddThh:mm:ss+hh:mm
                        written to [/domain-controller/historical-error-list[n]/timestamp]'
      writeEsAddress:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - es-address
                properties:
                  es-address:
                    type: object
                    description: >
                      'ElasticSearch index address
                      from [/load-es-addresses/es-address=*]
                      to be written into [/domain-controller/es-address=[/load-es-addresses/es-address/es-name]]'
        # #TODO falls man das doch angegben wollen würde, kann man das analog zum DPMDP Bsp unten machen
        # hier wird ja nur geschrieben, deshalb könnte man es auch weglassen
        #output:
        #  success:
        #    description: 'ES address written'
        #  error:
        #    description: 'Writing of ES address failed'

paths:
  /:
    description: 'no rest path provided by this module'


# Bsp von DPMDP
# p1StreamPmData: interface.yaml
# -> p1ProcessDevice
#      input: ...
#      output:
#        success:
#          description: 'PM data processed, sent and stored'
#        error:
#          description: 'Processing of PM data failed'