openapi: 3.0.0
info:
  title: p1LoadEsAddresses
  version: 1.0.0

x-javascript-interface:
  p1LoadEsAddresses:
    summary: 'Loads ES addresses and makes them available at DomainController'
    processing:
      p1LoadParameters:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - function-name
                properties:
                  function-name:
                    type: string
                    description: >
                      'Name of the Function whose parameters are to be loaded from the configFile
                      from [/load-es-addresses/function-name]'
        output:
          success:
            description: 'Parameters successfully loaded'
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    parameters:
                      type: object
                    config-file:
                      type: object
          error:
            description: 'Parameters could not be loaded'
            content:
              application/json:
                schema:
                  type: string
      p1ResolveEsAddress:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - parameters
                  - config-file
                  - es-name
                properties:
                  parameters:
                    type: object
                    description: >
                      'Hierarchical object holding the parameter settings
                      from [/load-es-addresses/parameters/sub-function=p1ResolveEsAddress]'
                  config-file:
                    type: object
                    description: >
                      'configFile content
                      from [/load-es-addresses/config-file]'
                  es-name:
                    type: string
                    description: >
                      'ElasticSearch name
                      from [/load-es-addresses/es-address=*/name]'
        output:
          success:
            description: 'ES address successfully resolved'
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    es-address:
                      type: object
          error:
            description: 'ES address could not be resolved'
            content:
              application/json:
                schema:
                  type: string
      makeAddressAvailableAtDomainController:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - name
                  - address
                properties:
                  name:
                    type: string
                    description: >
                      'ElasticSearch index name
                      from [/load-es-addresses/es-address=*/name]
                      to be written into [/domain-controller/elastic-search-addresses[*]/name]'
                  address:
                    type: object
                    description: >
                      'ElasticSearch index address
                      from [/load-es-addresses/es-address=*/address]
                      to be written into [/domain-controller/elastic-search-addresses[*]/address]'
        output:
          sucess:
            description: 'ES address made available at DomainController'
            content:
              schema:
                schema:
                  type: string
                  enum:
                    - 'ES address made available'
          error:
            description: 'ES address could not be made available at DomainController'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'ES address could not be made available'


# TODO
# - Das DomainController-Schema enthält keine ES-Attribute -> Schema erweitern?
# - Eine der ES-Adressen ist die Adresse vom DomainController selbst...


paths:
  /:
    description: 'no rest path provided by this module'