@startuml createOrUpdateDeviceGroup
skinparam responseMessageBelowArrow true

title
  createOrUpdateDeviceGroup
end title

participant "requestor\n" as requestor
participant "createOrUpdateDeviceGroup\n" as cur
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> cur: { deviceGroupLabel,\n<color:LightGray>deviceModelName,\n<color:LightGray>purgeDate</color> }
activate cur

  note over cur
    Checks whether given
    deviceGroupLabel exists
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS

  ' if deviceGroup does not exist
  group Checks applied in case DeviceGroup not existing
    note over cur
      IF DeviceGroup NOT existing:
    end note
    note right cur
      THEN <color:LightGray>(=new DeviceGroup)</color>
    end note
      note right cur
        IF deviceModelName NOT given
      end note
      note left cur
        THEN
      end note
      requestor <-- cur: { ErrorCode,\nErrorMessage,\n[attributeList] }

      note right cur
        Checks whether given
        deviceModelName exists
      end note
      cur -> RunDS
      activate RunDS
      cur <-- RunDS
      deactivate RunDS
      note right cur
        IF DeviceModel NOT existing:
      end note
      note left cur
        THEN
      end note
      requestor <-- cur: { ErrorCode,\nErrorMessage,\n[attributeList] }
    end group

  ' if deviceGroup already exists
  group Checks applied in case DeviceGroup already exists

    note over cur
      ELSE <color:LightGray>(=DeviceGroup already existing)</color>
    end note

      ' DeviceModelName given but mismatch
      group Insufficient DeviceModelName
        note over cur
          IF deviceModelName given
        end note
        note right cur
          THEN
        end note
        note right cur
          Checks whether given
          deviceModelName is equal
          to _deviceModel at given
          DeviceGroup
        end note
        note right cur
          Reads _deviceModel
          at given DeviceGroup
        end note
        cur -> RunDS
        activate RunDS
        cur <-- RunDS
        deactivate RunDS
        note right cur
          _IF deviceModelName NOT 
          equal to _deviceModel:
        end note
        note left cur
          _THEN
        end note
        requestor <-- cur: { ErrorCode,\nErrorMessage }
        end group

    ' now check if purgeDate is given
    group PurgeDate checks
      note over cur
        IF purgeDate is given:
      end note
      note right cur
        THEN
      end note
      note right cur
        Checks whether given
        purgeDate is allowed
      end note
        note right cur
          Reads defaultDeviceGroup
          from deviceModel referred
          by given DeviceGroup
        end note
        cur -> RunDS
        activate RunDS
        cur <-- RunDS
        deactivate RunDS
      note right cur
        _IF given deviceGroupLabel
        equals defaultDeviceGroup
      end note
      note left cur
        THEN
      end note
      requestor <-- cur: { ErrorCode,\nErrorMessage }
      note right cur
        Checks whether given
        purgeDate is reasonable
      end note
      note right cur
        _IF purgeDate already in past
      end note
      note left cur
        THEN
      end note
      requestor <-- cur: { ErrorCode,\nErrorMessage,\n[attributeList] }
    end group

  end group

' hier passiert zeug wenn der input geprüft wurde
  note over cur
    Locks RunningDS
  end note
  cur -X RunDS
  activate RunDS
  note over cur
    Locks CandidateDS
  end note
  cur -X CanDS
  activate CanDS
  note over cur
    Overwrites
    CandidateDS
    with RunningDS
  end note
  cur -> RunDS
  RunDS -/ CanDS

  note over cur
    IF deviceGroupLabel existing:
  end note
  note right cur
    THEN
  end note
  note right cur
    Updates DeviceGroup
  end note
  cur -> CanDS
  cur <-- CanDS
  note right cur
    ELSE
  end note
  note right cur
    Creates new DeviceGroup
  end note
  cur -> CanDS
  cur <-- CanDS

  note over cur
    Triggers Validation
  end note
  cur -> valiMan: {triggerFunction==createOrUpdateDeviceGroup}
  activate valiMan
    note over valiMan
      Validates
    end note
  cur <-- valiMan
  deactivate valiMan
  note over cur
    IF validation failed:
  end note
  note right cur
    THEN
  end note
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  requestor <-- cur: { ErrorCode,\nErrorMessage }
  note over cur
    ELSE
  end note

  note right cur
    Overwrites RunningDS
    with CandidateDS
  end note
  cur -> CanDS
  CanDS -\ RunDS
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  deactivate CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  deactivate RunDS

  requestor <-- cur: 204

deactivate cur

@enduml
