@startuml p1PurgeDeviceGroups
skinparam responseMessageBelowArrow true

title
  p1PurgeDeviceGroups
end title

participant "pulser\n" as requestor
participant "p1PurgeDeviceGroups\n" as indServ
participant "/deleteDeviceGroup\n" as delGroup
participant "p1ValidationManager\n" as valiMan
database "RunningDS" as RunDS

requestor -> indServ
activate indServ

  loop for each DeviceGroup
    note over indServ
      Reads DeviceGroup
    end note
    indServ -> RunDS
    activate RunDS
    indServ <-- RunDS: {label, purgeDate ... }
    deactivate RunDS
    note over indServ
      IF purgeDate exceeded:
    end note
    note over indServ
      THEN {
    end note
  note right indServ
    Deletes outdated DeviceGroup
    by calling /deleteDeviceGroup
  end note
    indServ -> delGroup: { label }
    activate delGroup
      note over delGroup
        Deletes DeviceGroup
        Adds Devices to default DeviceGroup
        Updates [firmwareList] of Devices
      end note
    indServ <-- delGroup: { ErrorCode,\nErrorMessage }
    deactivate delGroup

    note right indServ
      IF ResponseCode != 204:
    end note
    note right indServ
      THEN {
    end note
    note right indServ
      Append label to
      [unpurgedDevice]
    end note
    note right indServ
      }
    end note
    note over indServ
      }
    end note
  end loop

  note over indServ
    IF [unpurgedDevice].length > 0:
  end note
  note left indServ
    THEN {
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage1,\n[unpurgedDevice] }
  note left indServ
    }
  end note

requestor <-- indServ: 204
deactivate indServ

@enduml
