@startuml p1PurgeDeviceGroups
skinparam responseMessageBelowArrow true

title
  p1PurgeDeviceGroups
end title

participant "pulser\n" as pulser
participant "p1PurgeDeviceGroups\n" as cur
participant "/deleteDeviceGroup\n" as delGroup
participant "p1ValidationManager\n" as valiMan
database "RunningDS" as RunDS

pulser -> cur
activate cur

  loop for [DeviceGroup]
    note over cur
      Reads purgeDate
      of DeviceGroup
    end note
    cur -> RunDS
    activate RunDS
    cur <-- RunDS
    deactivate RunDS
    note over cur
      IF purgeDate exceeded:
    end note
    note right cur
      THEN
    end note
    note right cur
      Initiates deletion of DeviceGroup
    end note
    cur -> delGroup : { deviceGroupLabel }
    activate delGroup
      note over delGroup
        Deletes DeviceGroup
        Adds Devices to default DeviceGroup
        Updates [firmwareList] of Devices
      end note
    cur <-- delGroup
    deactivate delGroup
    note right cur
      <color:LightGray>ignores any errors</color>
    end note
    note over cur
      ELSE
    end note
  end loop

pulser <-- cur: 204
deactivate cur

@enduml
