@startuml p1UpdateFw
skinparam responseMessageBelowArrow true

title
  p1UpdateFw
end title

participant "requestor\n" as requestor
participant "p1UpdateFw\n" as indServ
participant "<i>functionName</i>\n" as extrFunc

database "DomainController" as DC
database "ErrorList" as hEL

requestor -> indServ: updatedMountName,\nCC
activate indServ

  note over indServ
    Extracts deviceModel
    from CC
  end note

  note over indServ
    Reads name of function for
    extracting firmware info
    from Parameters
  end note
  indServ -> DC: deviceModel
  activate DC
  indServ <-- DC: functionName
  deactivate DC
  note over indServ
    IF failed OR 
      functionName=="" or null:
  end note
  note right indServ
    THEN {
  end note
  indServ -> hEL: {functionName="p1UpdateFw",\nerrorMessage1}
  requestor <-- indServ: { ErrorCode,\nErrorMessage1 }
  note right indServ
    }
  end note

  note over extrFunc #White
    Parameters cannot define a set of input parameters.
    All functions get called with updatedMountName and CC.
  end note

  note over indServ
    Calls functionName
  end note
  indServ -> extrFunc: updatedMountName,\nCC
  activate extrFunc
    note over extrFunc
      Extracts firmware info
      and updates OperationalDS
    end note
  indServ <-- extrFunc
  deactivate extrFunc

requestor <-- indServ: 204
deactivate indServ

@enduml
