@startuml listExistingServers
skinparam responseMessageBelowArrow true

title
  listExistingServers
end title

participant "requestor\n" as requestor
participant "listExistingServers\n" as cur
database "RunningDS" as RunDS

requestor -> cur
activate cur

  note over cur
    Retrieves Servers
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS

requestor <-- cur: [ { serverLabel,\nuserName,\npassword,\nsshKey } ]
deactivate cur

@enduml
