@startuml updateFirmwareResource
skinparam responseMessageBelowArrow true

title
  updateFirmwareResource
end title

participant "requestor\n" as requestor
participant "updateFirmwareResource\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { firmwareResourceName,\nfirmwareResourceVersion,\n<color:LightGray>serverLabel,\n<color:LightGray>sourceUri,\n<color:LightGray>fileName</color> }
activate indServ

  note over indServ
    Checks, whether given
    combination of
    firmwareResourceName and
    firmwareResourceVersion
    already exists
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF FirmwareResource NOT existing:
  end note
  note left indServ
    THEN {
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage1,\n[attributeList] }
  note left indServ
    }
  end note

  note over indServ
    Checks whether potentially
    given serverLabel exists
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF serverLabel is given
      AND NOT existing:
  end note
  note left indServ
    THEN {
  end note  
  requestor <-- indServ: { ErrorCode,\nErrorMessage2,\n[attributeList] }
  note left indServ
    }
  end note

  note over indServ
    Checks, whether given
    combination of serverLabel,
    sourceUri and fileName
    already documented
  end note
  loop for each existing FirmwareResource
    note right indServ
      Read FirmwareResource
    end note
    indServ -> RunDS
    activate RunDS
    indServ <-- RunDS
    deactivate RunDS
    note right indServ
      IF given combination of serverLabel,
      sourceUri and fileName found:
    end note
    note left indServ
      THEN {
    end note
    requestor <-- indServ: { ErrorCode,\nErrorMessage3,\nfirmwareResourceName }
    note left indServ
      }
    end note
  end loop

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note over indServ
    Uses provided attributes for
    updating FirmwareResource
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==updateFirmwareResource}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note right indServ
    THEN {
  end note
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  requestor <-- indServ: { ErrorCode,\nErrorMessage4 }
  note right indServ
    }
  end note

  note over indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note over indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note over indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

requestor <-- indServ: 204
deactivate indServ

@enduml
