openapi: 3.0.0
info:
  title: p1ReduceData
  version: 1.0.0

x-javascript-interface:
  p1ReduceData:
    summary: 'Filters a provided data structure according to a provided fields filter string by using an in-place reduce approach, while following the syntax and function of the NETCONF definitions.'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - data-structure
              - fields-filter-string
            properties:
              data-structure:
                type: object
                description: 'The data structure to be filtered according to the provided fields filter string'
              fields-filter-string:
                type: string
                description: 'Fields filter string following NETCONF FieldsFilter syntax and semantics to be applied to the data structure'
    output:
      success:
        description: 'Data structure successfully filtered according to the provided fields filter string'
        content:
          application/json:
            schema:
              type: object
              required:
                - filtered-data-structure
              properties:
                filtered-data-structure:
                  type: object
                  description: >
                    'The data structure after filtering according to the provided fields filter string
                    from [/reduce-data/filtered-data-structure]'
      error:
        description: 'Data structure could not be filtered according to the provided fields filter string'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'dataStructure not provided'
                - 'dataStructure invalid'
                - 'fieldsFilterString not provided'
                - 'fieldsFilterString invalid'
                - 'filteredDataStructure could not be provided'
                - 'general processing error'
    processing:
      description: 'No requests or calls to other Functions'

paths:
  /:
    description: 'no rest path provided by this module'