@startuml listExistingFirmwareApprovals
skinparam responseMessageBelowArrow true

title
  listExistingFirmwareApprovals
end title

participant "requestor\n" as requestor
participant "listExistingFirmwareApprovals\n" as indServ
database "RunningDS" as RunDS

requestor -> indServ: { deviceModelName }
activate indServ

  note over indServ
    Retrieves data
    from RunningDS
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS

requestor <-- indServ: [ approvalList ]
deactivate indServ

@enduml
