@startuml listExistingFirmwareApprovals
skinparam responseMessageBelowArrow true

title
  listExistingFirmwareApprovals
end title

participant "requestor\n" as requestor
participant "listExistingFirmwareApprovals\n" as cur
database "RunningDS" as RunDS

requestor -> cur: { deviceModelName }
activate cur

  note over cur
    Retrieves approvals
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS

requestor <-- cur: [ approvalList ]
deactivate cur

@enduml
