@startuml provideExistingDeviceGroup
skinparam responseMessageBelowArrow true

title
  provideExistingDeviceGroup
end title

participant "requestor\n" as requestor
participant "provideExistingDeviceGroup\n" as cur
database "RunningDS" as RunDS

requestor -> cur: { deviceGroupLabel }
activate cur

  note over cur
    Retrieves DeviceGroup
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS

requestor <-- cur: { deviceGroupLabel,\ndeviceModelName,\n<color:LightGray>purgeDate</color>,\n[{targetFirmwareList}],\n[deviceList] }
deactivate cur

@enduml
