@startuml provideExistingDeviceGroup
skinparam responseMessageBelowArrow true

title
  provideExistingDeviceGroup
end title

participant "requestor\n" as requestor
participant "provideExistingDeviceGroup\n" as indServ
database "RunningDS" as RunDS

requestor -> indServ: { deviceGroupLabel }
activate indServ

  note over indServ
    Retrieves DeviceGroup
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS

requestor <-- indServ: { deviceGroupLabel,\ndeviceModelName,\n<color:LightGray>purgeDate</color>,\n[{targetFirmwareList}],\n[deviceList] }
deactivate indServ

@enduml
