@startuml createDeviceModel
skinparam responseMessageBelowArrow true

title
  createDeviceModel
end title

participant "requestor\n" as requestor
participant "createDeviceModel\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { deviceModelName }
activate indServ

  note over indServ
    Checks, whether
    DeviceModel
    already exists
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF DeviceModel already exists:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: 204
  note over indServ
    ELSE
  end note  

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note over indServ
    Creates DeviceModel
  end note
  indServ -> CanDS: { name==deviceModelName,\n_defaultDeviceGroup==deviceModelName }
  indServ <-- CanDS

  note over indServ
    Creates default DeviceGroup
  end note
  indServ -> CanDS: { label==deviceModelName,\n_deviceModel==deviceModelName }
  indServ <-- CanDS

  note over indServ
    Adds all existing Devices with
    deviceModel==deviceModelName
    to default DeviceGroup
  end note
  loop for each existing Device
    note over indServ
      Reads deviceModel
    end note
    indServ -> CanDS
    indServ <-- CanDS
    note over indServ
      IF deviceModel==deviceModelName:
    end note
    note right indServ
      THEN
    end note
    note right indServ
      Appends mountName to
      _device of default DeviceGroup
    end note
    indServ -> CanDS
    indServ <-- CanDS
  end loop

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==createDeviceModel}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note right indServ
    THEN
  end note
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  requestor <-- indServ: { ErrorCode,\nErrorMessage }
  note over indServ
    ELSE
  end note

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

  requestor <-- indServ: 204

deactivate indServ

@enduml
