@startuml addDevicesToDeviceGroup
skinparam responseMessageBelowArrow true

title
  addDevicesToDeviceGroup
end title

participant "requestor\n" as requestor
participant "addDevicesToDeviceGroup\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { deviceGroupLabel,\n[mountNameList] }
activate indServ

  note over indServ
    Checks whether given
    deviceGroupLabel exists
    by reading the deviceModel
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS: DeviceGroup::deviceModel
  deactivate RunDS
  note over indServ
    IF DeviceGroup NOT existing:
  end note
  note left indServ
    THEN {
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage1,\n[attributeList] }
  note left indServ
    }
  end note

  loop for each Device given in [mountNameList]
    note over indServ
      Checks whether
        - given mountName exists by reading deviceModel
        - Device::deviceModel equals DeviceGroup::deviceModel
    end note
    indServ -> RunDS
    activate RunDS
    indServ <-- RunDS: Device::deviceModel
    deactivate RunDS
    note over indServ
      IF Device NOT existing:
    end note
    note right indServ
      THEN {
    end note
    note right indServ
      Add mountName to [unknownDevice]
    end note
    note right indServ
      }
    end note
    note over indServ
      IF Device::deviceModel 
          != DeviceGroup::deviceModel
    end note
    note right indServ
      THEN {
    end note
    note right indServ
      Add mountName to [wrongTypeDevice]
    end note
    note right indServ
      }
    end note
  end loop
  note over indServ
    IF [unknownDevice].length > 0:
  end note
  note left indServ
    THEN {
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage2,\n[unknownDevice] }
  note left indServ
    }
  end note
  note over indServ
    IF [wrongTypeDevice].length > 0:
  end note
  note left indServ
    THEN {
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage3,\n[wrongTypeDevice] }
  note left indServ
    }
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  loop for each Device given in [mountNameList]
    note over indServ
      Deletes given mountName from
      [device] of all DeviceGroups
    end note
    loop for each DeviceGroup
      note over indServ
        Checks, whether mountName
        in [device] at DeviceGroup
      end note
      indServ -> CanDS
      indServ <-- CanDS
      note over indServ
        IF mountName in [device]:
      end note
      note right indServ
        THEN {
      end note
      note right indServ
        Deletes mountName from [device]
      end note
      indServ -> CanDS
      indServ <-- CanDS
      note right indServ
        }
      end note
    end loop

    note over indServ
      Adds given mountName to
      [device] at given DeviceGroup
    end note
    indServ -> CanDS
    indServ <-- CanDS

    note over indServ
      Deletes existing contents
      of [firmwareList] at Device
    end note
    indServ -> CanDS
    indServ <-- CanDS

    note over indServ
      Transfers content of 
      [targetFirmwareList]
      of DeviceGroup into
      [firmwareList] at Device
    end note
    note right indServ
      Reads [targetFirmwareList] at DeviceGroup
    end note
    indServ -> CanDS
    indServ <-- CanDS
    note right indServ
      Updates [firmwareList] at Device
    end note
    indServ -> CanDS
    indServ <-- CanDS
  end loop

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==addDevicesToDeviceGroup}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note right indServ
    THEN {
  end note
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  requestor <-- indServ: { ErrorCode,\nErrorMessage4 }
  note right indServ
    }
  end note

  note over indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note over indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note over indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

requestor <-- indServ: 204
deactivate indServ

@enduml
