@startuml addDevicesToDeviceGroup
skinparam responseMessageBelowArrow true

title
  addDevicesToDeviceGroup
end title

participant "requestor\n" as requestor
participant "addDevicesToDeviceGroup\n" as addDevice
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> addDevice: { deviceGroupLabel,\n[mountNameList] }
activate addDevice

  note over addDevice
    Checks whether given deviceGroupLabel
    exists by retrieving the DeviceGroup's
    targetFirmwareList
  end note
  addDevice -> RunDS
  activate RunDS
  addDevice <-- RunDS
  deactivate RunDS
  note over addDevice
    IF DeviceGroup NOT existing:
  end note
  note left addDevice
    THEN
  end note
  requestor <-- addDevice: { ErrorCode,\nErrorMessage,\n[attributeList] }
  note over addDevice
    ELSE
  end note

  note over addDevice
    Checks whether any given
    Devices are not existing by 
    retrieving their deviceModel
  end note
  loop for each mountName in mountNameList
    addDevice -> RunDS
    activate RunDS
    addDevice <-- RunDS
    deactivate RunDS
  end loop
  note over addDevice
    IF any Devices NOT existing:
  end note
  note left addDevice
    THEN
  end note
  requestor <-- addDevice: { ErrorCode,\nErrorMessage,\n[mountNameList] }
  note over addDevice
    ELSE
  end note

  note over addDevice
    Checks whether any given
    Devices have different 
    deviceModel than given
    DeviceGroup
  end note
  note over addDevice
    IF any Devices of the wrong deviceModel:
  end note
  note left addDevice
    THEN
  end note
  requestor <-- addDevice: { ErrorCode,\nErrorMessage,\n[mountNameList] }
  note over addDevice
    ELSE
  end note

  note over addDevice
    Locks RunningDS
  end note
  addDevice -X RunDS
  activate RunDS
  note over addDevice
    Locks CandidateDS
  end note
  addDevice -X CanDS
  activate CanDS
  note over addDevice
    Overwrites
    CandidateDS
    with RunningDS
  end note
  addDevice -> RunDS
  RunDS -/ CanDS

  loop for each given mountName
    note over addDevice
      Deletes given mountName from
      _device of other DeviceGroups
    end note
    loop for each DeviceGroup
      note over addDevice
        Checks, whether mountName
        in _device of DeviceGroup
      end note
      addDevice -> CanDS
      addDevice <-- CanDS
      note over addDevice
        IF mountName in _device:
      end note
      note right addDevice
        THEN
      end note
      note right addDevice
        Deletes mountName from _device
      end note
      addDevice -> CanDS
      addDevice <-- CanDS
      note over addDevice
        ELSE
      end note
    end loop

    note over addDevice
      Adds given mountName to
      _device at given DeviceGroup
    end note
    addDevice -> CanDS
    addDevice <-- CanDS

    note over addDevice
      Deletes existing contents
      of firmwareList at Device
    end note
    addDevice -> CanDS
    addDevice <-- CanDS

    note over addDevice
      Copies content of 
      targetFirmwareList
      of DeviceGroup into
      firmwareList at Device
    end note
    addDevice -> CanDS
    addDevice <-- CanDS
  end loop

  note over addDevice
    Triggers Validation
  end note
  addDevice -> valiMan: {triggerFunction==addDevicesToDeviceGroup}
  activate valiMan
    note over valiMan
      Validates
    end note
  addDevice <-- valiMan
  deactivate valiMan
  note over addDevice
    IF validation failed:
  end note
  note left addDevice
    THEN
  end note
  requestor <-- addDevice: { ErrorCode,\nErrorMessage }
  note over addDevice
    ELSE
  end note

  note right addDevice
    Overwrites RunningDS
    with CandidateDS
  end note
  addDevice -> CanDS
  CanDS -\ RunDS
  note right addDevice
    Unlocks CandidateDS
  end note
  addDevice -X CanDS
  deactivate CanDS
  note right addDevice
    Unlocks RunningDS
  end note
  addDevice -X RunDS
  deactivate RunDS

  requestor <-- addDevice: 204

deactivate addDevice

@enduml
