@startuml removeDevicesFromDeviceGroup
skinparam responseMessageBelowArrow true

title
  removeDevicesFromDeviceGroup
end title

participant "requestor\n" as requestor
participant "removeDevicesFromDeviceGroup\n" as cur
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> cur: { deviceGroupLabel,\n[mountNameList] }
activate cur

  note over cur
    Checks, whether
    given DeviceGroup
    is defaultDeviceGroup
  end note
  note right cur
    Reads deviceModel
    from given DeviceGroup
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS
  note right cur
    IF deviceGroupLabel NOT existing
  end note
  note right cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage,\n[attributeList] }
  note right cur
    ELSE
  end note

  note right cur
    Reads defaultDeviceGroup
    from this DeviceModel
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS
  note over cur
    IF given DeviceGroup
    equals defaultDeviceGroup:
  end note
  note left cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage }
  note over cur
    ELSE
  end note

  note over cur
    Reduces list of given
    mountNames to those that
    are actually referenced
    by given DeviceGroup
  end note
  note right cur
    Reads _device from
    given DeviceGroup
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS
  note over cur
    IF remaining list of to be
    removed mountNames empty:
  end note
  note left cur
    THEN
  end note
  requestor <-- cur: 204
  note over cur
    ELSE
  end note

  note over cur
    Locks RunningDS
  end note
  cur -X RunDS
  activate RunDS
  note over cur
    Locks CandidateDS
  end note
  cur -X CanDS
  activate CanDS
  note over cur
    Overwrites
    CandidateDS
    with RunningDS
  end note
  cur -> RunDS
  RunDS -/ CanDS

    note right cur
      Reads contents of
      targetFirmwareList
      at default DeviceGroup
    end note
    cur -> CanDS
    cur <-- CanDS

  loop for each remaining given mountName
    note right cur
      Deletes mountName from device
      list at given DeviceGroup
    end note
    cur -> CanDS
    cur <-- CanDS

    note right cur
      Deletes contents of 
      firmwareList at Device
    end note
    cur -> CanDS
    cur <-- CanDS

    note right cur
      Appends mountName to device
      list at defaultDeviceGroup
    end note
    cur -> CanDS
    cur <-- CanDS

    note right cur
      Writes contents of targetFirmwareList
      at default DeviceGroup into firmwareList
      at Device
    end note
    cur -> CanDS
    cur <-- CanDS
  end loop

  note over cur
    Triggers Validation
  end note
  cur -> valiMan: {triggerFunction==removeDevicesFromDeviceGroup}
  activate valiMan
    note over valiMan
      Validates
    end note
  cur <-- valiMan
  deactivate valiMan
  note over cur
    IF validation failed:
  end note
  note right cur
    THEN
  end note
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  requestor <-- cur: { ErrorCode,\nErrorMessage }
  note over cur
    ELSE
  end note

  note right cur
    Overwrites RunningDS
    with CandidateDS
  end note
  cur -> CanDS
  CanDS -\ RunDS
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  deactivate CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  deactivate RunDS

requestor <-- cur: 204
deactivate cur

@enduml
