@startuml listExistingDeviceGroups
skinparam responseMessageBelowArrow true

title
  listExistingDeviceGroups
end title

participant "requestor\n" as requestor
participant "listExistingDeviceGroups\n" as cur
database "RunningDS" as RunDS

requestor -> cur
activate cur

  note over cur
    Retrieves DeviceGroups
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS

requestor <-- cur: [ {deviceGroupLabel,\ndeviceModelName} ]
deactivate cur

@enduml
