@startuml listExistingDeviceGroups
skinparam responseMessageBelowArrow true

title
  listExistingDeviceGroups
end title

participant "requestor\n" as requestor
participant "listExistingDeviceGroups\n" as indServ
database "RunningDS" as RunDS

requestor -> indServ
activate indServ

  note over indServ
    Retrieves DeviceGroups
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS

requestor <-- indServ: [ {deviceGroupLabel,\ndeviceModelName} ]
deactivate indServ

@enduml
