@startuml updateDeviceGroup
skinparam responseMessageBelowArrow true

title
  updateDeviceGroup
end title

participant "requestor\n" as requestor
participant "updateDeviceGroup\n" as cur
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> cur: { deviceGroupLabel,\n<color:LightGray>purgeDate</color> }
activate cur

  note over cur
    Checks whether given
    deviceGroupLabel exists
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS
  deactivate RunDS
  note over cur
    IF DeviceGroup NOT existing:
  end note
  note left cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage1,\n[attributeList] }
  note over cur
    ELSE
  end note

  note over cur
    Checks whether potentially
    given purgeDate is reasonable
  end note
  note over cur
    IF purgeDate is given 
        AND already in past:
  end note
  note left cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage2,\n[attributeList] }
  note over cur
    ELSE
  end note

  note over cur
    Checks whether potentially
    given purgeDate would be 
    allowed to be updated
  end note
  note over cur
    IF purgeDate is given:
  end note
  note right cur
    THEN
  end note
  note right cur
    Reads deviceModel
    of given DeviceGroup
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS: { deviceModel }
  deactivate RunDS
  note right cur
    Reads defaultDeviceGroup
    of deviceModel
  end note
  cur -> RunDS
  activate RunDS
  cur <-- RunDS: { defaultDeviceGroup }
  deactivate RunDS
  note right cur
    IF given DeviceGroup == defaultDeviceGroup:
  end note
  note left cur
    THEN
  end note
  requestor <-- cur: { ErrorCode,\nErrorMessage3,\n[attributeList] }
  note right cur
    ELSE
  end note
  note over cur
    ELSE
  end note

  note over cur
    Locks RunningDS
  end note
  cur -X RunDS
  activate RunDS
  note over cur
    Locks CandidateDS
  end note
  cur -X CanDS
  activate CanDS
  note over cur
    Overwrites
    CandidateDS
    with RunningDS
  end note
  cur -> RunDS
  RunDS -/ CanDS

  note over cur
    Uses provided attributes
    for updating DeviceGroup
  end note
  cur -> CanDS
  cur <-- CanDS

  note over cur
    Triggers Validation
  end note
  cur -> valiMan: {triggerFunction==updateDeviceGroup}
  activate valiMan
    note over valiMan
      Validates
    end note
  cur <-- valiMan
  deactivate valiMan
  note over cur
    IF validation failed:
  end note
  note right cur
    THEN
  end note
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  requestor <-- cur: { ErrorCode,\nErrorMessage4 }
  note over cur
    ELSE
  end note

  note right cur
    Overwrites RunningDS
    with CandidateDS
  end note
  cur -> CanDS
  CanDS -\ RunDS
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  deactivate CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  deactivate RunDS

requestor <-- cur: 204
deactivate cur

@enduml
