@startuml deleteDeviceGroup
skinparam responseMessageBelowArrow true

title
  deleteDeviceGroup
end title

participant "requestor\n" as requestor
participant "deleteDeviceGroup\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { deviceGroupLabel }
activate indServ

  note over indServ
    Checks, whether given
    DeviceGroup exists by
    reading its deviceModel
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF DeviceGroup NOT existing:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: 204
  note over indServ
    ELSE
  end note

  note over indServ
    Assures that given DeviceGroup
    is not default DeviceGroup
  end note
  note over indServ
    Reads defaultDeviceGroup
    of referenced DeviceModel
  end note  
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF given deviceGroupLabel
    equals defaultDeviceGroup:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage,\nreferencingDeviceModel }
  note over indServ
    ELSE
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note over indServ
    Reads [devices] at
    given DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Reads [targetFirmwareList]
    at default DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Deletes given
    DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS

  loop for [devices]
    note over indServ
      Appends mountName to [devices]
      of default DeviceGroup
    end note
    indServ -> CanDS
    indServ <-- CanDS

    note over indServ
      Transfers [targetFirmwareList]
      of default DeviceGroup to
      [firmwareList] of Device
    end note
    indServ -> CanDS
    indServ <-- CanDS
  end loop

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==deleteDeviceGroup}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note right indServ
    THEN
  end note
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  requestor <-- indServ: { ErrorCode,\nErrorMessage }
  note over indServ
    ELSE
  end note

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

requestor <-- indServ: 204
deactivate indServ

@enduml
