@startuml deleteDeviceGroup
skinparam responseMessageBelowArrow true

title
  deleteDeviceGroup
end title

participant "requestor\n" as requestor
participant "deleteDeviceGroup\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { deviceGroupLabel }
activate indServ

  note over indServ
    Checks, whether given
    deviceGroupLabel exists
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF DeviceGroup NOT existing:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: 204
  note over indServ
    ELSE
  end note

  note over indServ
    Checks, whether to be
    deleted DeviceGroup is
    a default DeviceGroup
  end note
  loop for each existing DeviceModel
    note over indServ
      Read defaultDeviceGroup
    end note  
    indServ -> RunDS
    activate RunDS
    indServ <-- RunDS
    deactivate RunDS
  end loop
  note over indServ
    IF given deviceGroupLabel
    exists in defaultDeviceGroup:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage,\nreferencingDeviceModel }
  note over indServ
    ELSE
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note over indServ
    Reads _devices at
    given DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS
  note over indServ
    IF number of Devices > 0:
  end note
  note right indServ
    THEN
  end note
  note right indServ
    Reads deviceModel
    at given DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS
  note right indServ
    Reads defaultDeviceGroup
    at this DeviceModel
  end note
  indServ -> CanDS
  indServ <-- CanDS
  note right indServ
    Appends all entries of _devices
    at given DeviceGroup to _devices
    at default DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note right indServ
    Deletes given DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==deleteDeviceGroup}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage }
  note over indServ
    ELSE
  end note

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

  requestor <-- indServ: 204

deactivate indServ

@enduml
