@startuml deleteServer
skinparam responseMessageBelowArrow true

title
  deleteServer
end title

participant "requestor\n" as requestor
participant "deleteServer\n" as delServer
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> delServer: { serverLabel }
activate delServer

  note over delServer
    Checks for server with
    given label to exist
  end note
  delServer -> RunDS
  activate RunDS
  delServer <-- RunDS
  deactivate RunDS
  note over delServer
    IF server NOT existing:
  end note
  note left delServer
    THEN
  end note
  requestor <-- delServer: 204
  note over delServer
    ELSE
  end note

  note over delServer
    Checks for any existing
    FirmwareResource to
    reference given server
  end note
  loop for each existing FirmwareResource
    delServer -> RunDS
    activate RunDS
    delServer <-- RunDS
    deactivate RunDS
  end loop
  note over delServer
    IF server still referenced:
  end note
  note left delServer
    THEN
  end note
  requestor <-- delServer: { ErrorCode,\nErrorMessage,\nlistOfReferencingFirmwareResources }
  note over delServer
    ELSE
  end note

  note over delServer
    Locks RunningDS
  end note
  delServer -X RunDS
  activate RunDS
  note over delServer
    Locks CandidateDS
  end note
  delServer -X CanDS
  activate CanDS
  note over delServer
    Overwrites
    CandidateDS
    with RunningDS
  end note
  delServer -> RunDS
  RunDS -/ CanDS

  note right delServer
    Deletes given server
  end note
  delServer -> CanDS
  delServer <-- CanDS

  note over delServer
    Triggers Validation
  end note
  delServer -> valiMan: {triggerFunction==deleteServer}
  activate valiMan
    note over valiMan
      Validates
    end note
  delServer <-- valiMan
  deactivate valiMan
  note over delServer
    IF validation failed:
  end note
  note left delServer
    THEN
  end note
  requestor <-- delServer: { ErrorCode,\nErrorMessage }
  note over delServer
    ELSE
  end note

  note right delServer
    Overwrites RunningDS
    with CandidateDS
  end note
  delServer -> CanDS
  CanDS -\ RunDS
  note right delServer
    Unlocks CandidateDS
  end note
  delServer -X CanDS
  deactivate CanDS
  note right delServer
    Unlocks RunningDS
  end note
  delServer -X RunDS
  deactivate RunDS

  requestor <-- delServer: 204

deactivate delServer

@enduml
