@startuml deleteServer
skinparam responseMessageBelowArrow true

title
  deleteServer
end title

participant "requestor\n" as requestor
participant "deleteServer\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { serverLabel }
activate indServ

  note over indServ #lightcoral
    hier analog, wenn die Validierung fehlschlägt,
    werden die beiden DS nicht unlocked.
    muss der ursprüngliche Zustand vom 
    Candidate wieder hergestellt werden?
  end note
  note over indServ #lightcoral
    werden der Candidate jeweils komplett mit dem Running
    überschrieben und umgekehrt?
    Falls ja, was ist mit pending validations?
    Theoretisch könnten die ja fortlaufend nötig sein.
  end note

  note over indServ
    Checks whether given
    serverLabel exists
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF Server NOT existing:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: 204
  note over indServ
    ELSE
  end note

  note over indServ
    Checks for any existing
    FirmwareResource to
    reference given Server
  end note
  loop for each existing FirmwareResource
    indServ -> RunDS
    activate RunDS
    indServ <-- RunDS
    deactivate RunDS
  end loop
  note over indServ
    IF Server still referenced:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage,\n[listOfReferencingObjects] }
  note over indServ
    ELSE
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note right indServ
    Deletes given Server
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==deleteServer}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note right indServ
    THEN
  end note
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  requestor <-- indServ: { ErrorCode,\nErrorMessage }
  note over indServ
    ELSE
  end note

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

  requestor <-- indServ: 204

deactivate indServ

@enduml
