@startuml p1CreateDevices
skinparam responseMessageBelowArrow true

title
  p1CreateDevices
end title

participant "pulser\n" as pulser
participant "p1CreateDevices\n" as cur
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS
database "OperationalDS" as OpDS


pulser -> cur
activate cur

  ' Read devices from ODS
  note over cur
    Reads list of ODS:Devices
  end note
  cur -> OpDS
  activate OpDS
  cur <-- OpDS
  deactivate OpDS


  ' Loop over ODS devices, add them to [newDevices]
  loop for each ODS:Device
    note over cur
      Checks, whether it can
      be found in RDS:Devices
    end note
    cur -> RunDS
    activate RunDS
    cur <-- RunDS
    deactivate RunDS
    note over cur
      IF cannot be found:
    end note
    note right cur
      THEN
    end note
    note right cur #LightCoral
      Imho fehlt hier ein Schritt, in dem
      das DeviceModel bestimmt wird
      (anhand des CC.deviceModelNames)
    end note

    note right cur
      Add mountName and deviceModel
      of ODS:Device to [newDevices]
    end note
    note over cur #lightBlue
      ELSE würde ich weglassen
      (beim Programmierung muss man ja auch
      kein else angeben, wenn es keins gibt)
    end note
    note over cur
      ELSE
    end note
  end loop
  note over cur
    IF [newDevices].length = 0:
  end note
  note left cur
    THEN
  end note
  pulser <-- cur: 204
  note over cur #lightBlue
    Else würde ich hier auch weglassen.
    das 204 terminiert ja.
  end note
  note over cur
    ELSE
  end note  

  ' Lock DataStores and copy RDS to CDS
  note over cur
    Locks RunningDS
  end note
  cur -X RunDS
  activate RunDS
  note over cur
    Locks CandidateDS
  end note
  cur -X CanDS
  activate CanDS
  note over cur
    Overwrites
    CandidateDS
    with RunningDS
  end note
  cur -> RunDS
  RunDS -/ CanDS

  ' Create new devices in RDS
  loop for [newDevices]
    note over cur
      Creates new RDS:Devices
    end note
    cur -> CanDS
    cur <-- CanDS

    note over cur
      Adds new RDS:Device
      to default DeviceGroup
    end note
    note over cur
      Attempts to address DeviceModel
      RDS:Device.deviceModel for reading its 
      defaultDeviceGroup
    end note
    cur -> CanDS
    cur <-- CanDS
    note over cur
      IF DeviceModel does not exist:
    end note
    note right cur
      THEN
    end note
    note right cur
      No further action
      at this Device
    end note
    note over cur
      ELSE
    end note
    note over cur
      Adds RDS:Device.mountName
      to [device] at defaultDeviceGroup
    end note
    cur -> CanDS
    cur <-- CanDS

    note over cur
      Transfers content of
      defaultDeviceGroup.[targetFirmwareList]
      to RDS:Device.[firmwareList]
    end note

    note right cur
      Reads [targetFirmwareList]
      at defaultDeviceGroup
    end note
    cur -> CanDS
    cur <-- CanDS
    note right cur
      Updates
      RDS:Device.[firmwareList]
    end note
    cur -> CanDS
    cur <-- CanDS
  end loop

  ' Write changes from CDS to RDS and unlock DataStores
  note right cur
    Overwrites RunningDS
    with CandidateDS
  end note
  cur -> CanDS
  CanDS -\ RunDS
  note right cur
    Unlocks CandidateDS
  end note
  cur -X CanDS
  deactivate CanDS
  note right cur
    Unlocks RunningDS
  end note
  cur -X RunDS
  deactivate RunDS

pulser <-- cur: 204
deactivate cur

@enduml
