@startuml createServer
skinparam responseMessageBelowArrow true

title
  createServer
end title

participant "requestor\n" as requestor
participant "createServer\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { serverLabel,\n<color:LightGray>userName,\n<color:LightGray>password,\n<color:LightGray>sshKey</color> }
activate indServ

  note over valiMan #Orange
    Es ist fachlich unklar welche Attribute
    zwingend benötigt werden, bzw. welche
    auch fehlen dürfen müssen.
    Ggf. sind Inputparameter hier schwarz zu
    markieren und in der openAPI als required
    zu dokumentieren.
  end note

  note over indServ
    Checks, whether given
    serverLabel already exists
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS
  deactivate RunDS
  note over indServ
    IF Server already exists:
  end note
  note left indServ
    THEN
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage1 }

  note over valiMan #Orange
    Ggf. wäre password auf
    Sicherheitsanforderungen
    zu prüfen.
  end note

  note over valiMan #Orange
    Ggf. wäre sshKey auf
    ein Pattern zu prüfen.
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note over indServ
    Creates new Server
    with provided attributes
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==createServer}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note right indServ
    THEN
  end note
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  requestor <-- indServ: { ErrorCode,\nErrorMessage2 }
  note over indServ
    ELSE
  end note

  note right indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

requestor <-- indServ: 204
deactivate indServ

@enduml
