@startuml addTargetFirmware
skinparam responseMessageBelowArrow true

title
  addTargetFirmware
end title

participant "requestor\n" as requestor
participant "addTargetFirmware\n" as indServ
participant "p1ValidationManager\n" as valiMan
database "CandidateDS" as CanDS
database "RunningDS" as RunDS

requestor -> indServ: { deviceGroupLabel,\nfirmwareResourceName,\nfirmwareResourceVersion,\nfirmwareStatus }
activate indServ

  note over indServ
    Checks whether given
    deviceGroupLabel exists
    by reading deviceModel
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS: deviceModel
  deactivate RunDS
  note over indServ
    IF DeviceGroup NOT existing:
  end note
  note left indServ
    THEN {
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage1,\n[attributeList] }
  note left indServ
    }
  end note

  note over indServ
    Checks whether given combination
    of firmwareResourceName and
    firmwareResourceVersion already
    referenced in targetFirmwareList
    of given DeviceGroup
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS: [targetFirmwareList]
  deactivate RunDS
  note over indServ
    IF FirmwareResource already
    referenced in targetFirmwareList:
  end note
  note left indServ
    THEN {
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage2 }
  note left indServ
    }
  end note

  note over indServ
    Checks whether given combination
    of firmwareResourceName and
    firmwareResourceVersion has
    been approved for deviceModel
  end note
  note over indServ
    Reads [approval] from DeviceModel
  end note
  indServ -> RunDS
  activate RunDS
  indServ <-- RunDS: [approval]
  deactivate RunDS
  note over indServ
    IF given combination of
    firmwareResourceName and
    firmwareResourceVersion
    NOT in [approval]:
  end note
  note left indServ
    THEN {
  end note
  requestor <-- indServ: { ErrorCode,\nErrorMessage3 }
  note left indServ
    }
  end note

  note over indServ
    Locks RunningDS
  end note
  indServ -X RunDS
  activate RunDS
  note over indServ
    Locks CandidateDS
  end note
  indServ -X CanDS
  activate CanDS
  note over indServ
    Overwrites
    CandidateDS
    with RunningDS
  end note
  indServ -> RunDS
  RunDS -/ CanDS

  note over indServ
    Appends another target firmware
    to the [targetFirmwareList] of the
    given DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS

  note over indServ
    Replicates the updated [targetFirmwareList]
    of given DeviceGroup into the [firmwareList]
    at the Devices referenced in [devices] of
    same DeviceGroup
  end note
  note left valiMan #Yellow
    Attention:
    There is no protection against
    too many TargetFirmware or wrong
    compositions of TargetFirmware!
  end note
  note right indServ
    Reads [device] at
    given DeviceGroup
  end note
  indServ -> CanDS
  indServ <-- CanDS: [device]
  loop for each referenced Device
    note right indServ
      Delete existing [firmwareList]
    end note
    indServ -> CanDS
    indServ <-- CanDS
    note right indServ
      Transfer [targetFirmwareList]
      of given DeviceGroup into
      [firmwareList] at the Device
    end note
    indServ -> CanDS
    indServ <-- CanDS
  end loop

  note over indServ
    Triggers Validation
  end note
  indServ -> valiMan: {triggerFunction==addTargetFirmware}
  activate valiMan
    note over valiMan
      Validates
    end note
  indServ <-- valiMan
  deactivate valiMan
  note over indServ
    IF validation failed:
  end note
  note right indServ
    THEN {
  end note
  note right indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  note right indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  requestor <-- indServ: { ErrorCode,\nErrorMessage4 }
  note right indServ
    }
  end note

  note over indServ
    Overwrites RunningDS
    with CandidateDS
  end note
  indServ -> CanDS
  CanDS -\ RunDS
  note over indServ
    Unlocks CandidateDS
  end note
  indServ -X CanDS
  deactivate CanDS
  note over indServ
    Unlocks RunningDS
  end note
  indServ -X RunDS
  deactivate RunDS

requestor <-- indServ: 204
deactivate indServ

@enduml
