@startuml hl_sequence
skinparam responseMessageBelowArrow true

title
  FirmWareManager
end title

participant "embedYourself\n" as embed
participant "p1ManageFirmware\n" as p1ManaFw
participant "p1LoadEsAddresses\n" as p1LEA
participant "p1LoadParameters\n" as p1LP #White
participant "p1ResolveEsAddress\n" as p1REA #White
participant "p1CreateDomainController\nFromStartupDS" as p1CDCFS
participant "p1Pulser\n" as p1Puls
database "ElasticSearch" as FwmEs

embed -> p1ManaFw
activate p1ManaFw

  p1ManaFw -> p1LEA
  activate p1LEA
    note over p1LEA
      Makes ElasticSearch
      addresses available
      in DomainController
    end note
    p1LEA -> p1LP
    activate p1LP
      note over p1LP
        Loads parameters
        from configFile
      end note
    p1LEA <-- p1LP
    deactivate p1LP
    p1LEA -> p1REA
    activate p1REA
      note over p1REA
        Resolves
        ES address
      end note
    p1LEA <-- p1REA
    deactivate p1REA
  p1ManaFw <-- p1LEA
  deactivate p1LEA

  p1ManaFw -> p1CDCFS
  activate p1CDCFS
    note over p1CDCFS
      Populates DomainController
      from ElasticSearch
    end note
    p1CDCFS -> p1LP
    activate p1LP
      note over p1LP
        Loads parameters
        from configFile
      end note
    p1CDCFS <-- p1LP
    deactivate p1LP
    p1CDCFS -> FwmEs
    activate FwmEs
    p1CDCFS <-- FwmEs
    deactivate FwmEs
  p1ManaFw <-- p1CDCFS
  deactivate p1CDCFS
  
  p1ManaFw -> p1Puls
  activate p1Puls
    note over p1Puls
      Cyclically
      invokes
      functions
    end note

@enduml
