@startuml listDeviceModelsWithoutApprovals
skinparam responseMessageBelowArrow true

title
  listDeviceModelsWithoutApprovals
end title

participant "requestor\n" as requestor
participant "listDeviceModelsWithoutApprovals\n" as cur
database "RunningDS" as RunDS

requestor -> cur
activate cur

    note over cur
      Retrieves [DeviceModels]
    end note
    cur -> RunDS
    activate RunDS
    cur <-- RunDS
    deactivate RunDS

  loop for each DeviceModel
    note over cur
      If [approval].length NOT > 0
    end note
    note right cur
      THEN
    end note
    note right cur
      Appends name of DeviceModel
      to [deviceModelList]
    end note
    note over cur
      ELSE
    end note
  end loop

requestor <-- cur: { [deviceModelList] }
deactivate cur

@enduml
